[package]
name = "rusty-app"
version = "0.1.0"
edition = "2024"

[dependencies]
mailparse = "0.7"
tokio = { version = "1.0", features = ["full"] }
pgp = "0.9"
gtk4 = { version = "0.8", package = "gtk4" }
glib = "0.18"
